"""Create UploadedText model

Revision ID: a15728691045
Revises: c2fe6859505c
Create Date: 2025-05-06 21:03:33.674475

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a15728691045'
down_revision = 'c2fe6859505c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    
    if 'uploaded_texts' in tables:
        columns = [column['name'] for column in inspector.get_columns('uploaded_texts')]
        if 'status' in columns:
            with op.batch_alter_table('uploaded_texts', schema=None) as batch_op:
                batch_op.drop_column('status')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), nullable=True))

    # ### end Alembic commands ###
