"""Create UploadedText table with title field

Revision ID: e81e4b56d61d
Revises: a15728691045
Create Date: 2025-05-06 21:10:36.357235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81e4b56d61d'
down_revision = 'a15728691045'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_texts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_texts', schema=None) as batch_op:
        batch_op.drop_column('title')

    # ### end Alembic commands ###
